name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Install dependencies
        run: go mod download
      - name: Check formatting
        run: |
          fmt_out=$(gofmt -l $(git ls-files '*.go'))
          if [ -n "$fmt_out" ]; then
            echo "Go files need formatting:" && echo "$fmt_out"
            exit 1
          fi
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test ./...
